/*
 *   IRC - Internet Relay Chat, src/version.c
 *   Copyright (C) 1990 Chelsea Ashley Dyerman
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 1, or (at your option)
 *   any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/*
 * This file is generated by version.c.SH. Any changes made will go away.
 */

#include "struct.h"
#include "patchlevel.h"

const char *creation = BUILD_TIME;
const char *version = PATCHLEVEL;
/* serial is now defined in the autogenerated svn_version.c -- jilles */
const char *platform = BUILD_UNAME;

const char *infotext[] =
{
  "IRC --",
  "(Distantly) based on the original code written by Jarkko Oikarinen",
  "Copyright 1988, 1989, 1990, 1991 University of Oulu, Computing Center",
  "",
  "This program is free software; you can redistribute it and/or",
  "modify it under the terms of the GNU General Public License as",
  "published by the Free Software Foundation; either version 2, or",
  "(at your option) any later version.",
  "",
  "Hyperion is freenode's continuation of dancer-ircd 1.0.35+pre2, and",
  "its development is led by Jilles Tjoelker <jilles@stack.nl>.",
  "",
  "Dancer-ircd is largely based on hybrid 6.x, and its ongoing support",
  "and enhancement was led by Andrew Suffield <asuffield@debian.org>.",
  "Thanks to Rik Rose <code@rikrose.net> for coding the original",
  "OPMODERATE feature and to tav <tav@espians.com> for the idea behind it.",
  "",
  "The concepts and many of the features of dancer ircd were formulated",
  "by Rob Levin <levin@freenode.net>, to meet the policy needs of the",
  "freenode (formerly OPN) IRC network.  Freenode (http://freenode.net/)",
  "is a service of the Peer-Directed Projects Center, a US IRS 501(c)(3)",
  "charitable and educational organization.",
  "",
  "Thanks to the developers of hybrid ircd (http://www.ircd-hybrid.net/),",
  "including Patrick Alken, Diane Bruce, Edward Brocklesby, Adel Mezibra,",
  "Bill Jonus, Jon Lusky and Joan Touzet."
  "",
  "Thanks also to the many people who contributed to the earlier releases,",
  "including Peter Abrahamsen, Justin Bajko, Draco Benden, Richard Brackman,",
  "Rob Bradford, Daniel Dent, David Graham, Andre Guibert de Bruet,",
  "Johnie Ingram, Gerard Mack, Daniel Jacobowitz, Gerard Oskamp, Rik Rose,",
  "John Rowan, and Matthew Sachs.  Remind us if we've left you out. ;)",
  "",
  "Please send any bug reports or comments to bugs@freenode.net.",
  "",
  0
};
